//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPKprojektDotNet.Datebase.I7
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarService
    {
        public int IDService { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
