//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPKprojektDotNet.Datebase.I7
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceItem
    {
        public int IDItem { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> CarServiceID { get; set; }
    
        public virtual CarService CarService { get; set; }
    }
}
