//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPKprojektDotNet.Datebase.I7
{
    using System;
    using System.Collections.Generic;
    
    public partial class travelWarrant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public travelWarrant()
        {
            this.Routes = new HashSet<Route>();
        }
    
        public int IDTwarrant { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> WarrantStateEnumId { get; set; }
    
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Route> Routes { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual WarrantStateEnum WarrantStateEnum { get; set; }
    }
}
